version: '3'

services:
    code-server:
        container_name: code-server
        image: sptkl/code:74e7481b0587
        restart: always
        ports:
          - 8080:8080
        volumes:
          - /home/coder/project:/home/coder/project
          - /var/run/docker.sock:/var/run/docker.sock
        env_file:
          - .env
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: always
        ports:
            - 8880:80
        env_file:
          - .env
